version: "3.8"
services:
  pg: 
    image: postgres
    container_name: app_users_db
    restart: always
    networks:
      - app_users_network
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 2345:5432

  app-users-api:
    build: .
    depends_on:
      - pg
    ports: 
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app_users_network

networks:
  app_users_network:
    driver: bridge